"""
Django settings for chat project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1fs9p9^cq$phimfic7!wppnz#)*aozr^9&z!b!!csn=yh@3e9^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'chatterbot.ext.django_chatterbot',
    'rest_framework',
    'chat_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chat.wsgi.application'
ASGI_APPLICATION = 'chat.wsgi.application'#added


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
#================== ALL ADDED LATTER
'''
CHATTERBOT = {
    'name': 'chat',
    'django_app_name': 'chat_app'

    trainer = ChatterBotCorpusTrainer(chatterbot) #added
    trainer.train(
                  #*settings.CHATTERBOT,
                 # "chatterbot.corpus.english.sports",
                 # "chatterbot.corpus.english.science",
                 # "chatterbot.corpus.english.movies",
                 # "chatterbot.corpus.english.humor",
                 # "chatterbot.corpus.english.health",
                  "chatterbot.corpus.english.greetings",
                 # "chatterbot.corpus.english.food",
                 # "chatterbot.corpus.english.emotion",
                 # "chatterbot.corpus.english.conversations",
                 # "chatterbot.corpus.english.computers",
                 # "chatterbot.corpus.english.botprofile"
                  
                 )
    
}
'''
#'''
CHATTERBOT = {
    'name': 'chat',
    'django_app_name': 'django_chatterbot',#'chat_app',*** always keep it default 
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': [
                  #"chatterbot.corpus.english.sports",
                  #"chatterbot.corpus.english.science",
                  #"chatterbot.corpus.english.movies",
                  #"chatterbot.corpus.english.humor",
                  #"chatterbot.corpus.english.health",
                  #"chatterbot.corpus.english.greetings",
                  #"chatterbot.corpus.english.food",
                  #"chatterbot.corpus.english.emotion",
                  #"chatterbot.corpus.english.conversations",
                  #"chatterbot.corpus.english.computers",
                  #"chatterbot.corpus.english.botprofile"
    ]
}

#web: https://www.tutorialdocs.com/tutorial/chatterbot/django-integration.html
#'''